name: Build Electron App

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4  # Atualizado para a versão mais recente

      - name: Instalar Node.js
        uses: actions/setup-node@v4  # Atualizado para v4
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Build para ${{ matrix.os }}
        run: npm run make

      - name: Upload dos instaladores gerados
        uses: actions/upload-artifact@v4  # Atualizado para v4
        with:
          name: build-${{ matrix.os }}
          path: out/

